### ISSUE TITLE
Can we add a "cancel" button to journal entry?

### ISSUE THREAD

**Issue by kidwellj** [bear-rsg/experiences-of-landscape-workers#31]
When drafting a journal entry... there's no "cancel" button if I want to scratch it and go back to main menu. I had to save to journal and then delete the entry.

**Comment by mike-allaway** [comment]
You can just click on any of the main navigation buttons to go to another page or even just refresh the current page to clear out a journal entry text box (i.e. reset the form). You don't have to save it and then delete it. We could add a 'clear text' button but I'm worried it may get accidentally tapped and users would lose their work.

If users do request an additional 'clear text' button then we can try adding it in a subsequent version, but I think it'll be fine without, if that's ok?

**Comment by kidwellj** [comment]
I agree - this sounds very sensible
