### ISSUE TITLE
Drafts not shared across devices

### ISSUE THREAD

**Issue by kidwellj** [bear-rsg/experiences-of-landscape-workers#33]
Again - maybe necessary by design, but seems like something that will befuddle multi-device users. Currently drafts only stored on the device where they are written.

**Comment by mike-allaway** [comment]
As touched on in #37 , drafts are by their nature device specific, not user specific (as they have work offline) so can't be accessed on different devices. So this isn't a bug, but I'll still add a point about it on the drafts page, advising users that if they want to edit on another device they'll need to submit it to their journal first (e.g. submit to our server, to the other device can retrieve it from our server).

**Comment by kidwellj** [comment]
Totally take your point here. Sounds good to me
