### ISSUE TITLE
No image for drafts

### ISSUE THREAD

**Issue by kidwellj** [bear-rsg/experiences-of-landscape-workers#34]
Looks like drafts can't have an image attached. So feature request maybe?

**Comment by mike-allaway** [comment]
Drafts are really just designed to allow users to write and store text when offline. Images can easily be stored offline on smartphones, just by taking a photo using their camera app and storing/accessing these with their photos app. Then the user can quickly and easily add photos taken offline to the journal entry form when ready to submit.

I've had a look into setting html files programmatically via JS (in this case, by taking a file from IndexedDB) but it gets quite messy. I think we should leave it as is, as mentioned above users can still store photos offline.

But if when we get feedback from users there's demand for this, then we can look to explore further in a subsequent version, if that's ok?
