### ISSUE TITLE
"Add Entry" written with internet on, turn internet off, "Save to Journal" = entry dropped

### ISSUE THREAD

**Issue by kidwellj** [bear-rsg/experiences-of-landscape-workers#35]
If I start something, and let's say my internet service drops before I click "Save to Journal" this effectively drops all the entry data and redirects me to the landing page suggesting I write a draft. Can we find a way to preserve data or funnel to a new draft entry? I can imagine scenarios where user may not even realise they have lost data and may have written something in great detail...

**Comment by mike-allaway** [comment]
Yes, this is totally valid, thanks for identifying this. I'll add a check as the form is being submitted to check for an internet connection and respond appropriately (e.g. don't even try to submit if no internet connection is found).
