### ISSUE TITLE
Drafts associated with device even when logged out. 

### ISSUE THREAD

**Issue by kidwellj** [bear-rsg/experiences-of-landscape-workers#37]
So if a user were to log out, and hand the device over to a friend, they log in with a new account, the drafts seem to be in a shared pool. Perhaps a security concern? Also drafts are visible when logged out.

**Comment by mike-allaway** [comment]
For drafts to work offline they have to be stored locally on the device in the IndexedDB. IndexedDB doesn't have user authentication, so anyone who has access to the device can see the drafts. Also, the user authentication requires an internet connection as it's handled by Django on the server, meaning if drafts were user-specific they wouldn't work offline.

So it's not necessarily a bug that needs to be fixed, but I'll still add a message to the Drafts page to highlight that drafts are linked to a device, not a user account, so they will be visible by anyone else using that device and it's the user's responsibility as the owner of the device to manage security of it.
